"""empty message

Revision ID: f9b870bdcf1b
Revises: 
Create Date: 2023-10-13 15:39:25.109675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b870bdcf1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Teams_Table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Fixtures_Table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=True),
    sa.Column('away_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['away_id'], ['Teams_Table.id'], name=op.f('fk_Fixtures_Table_away_id_Teams_Table')),
    sa.ForeignKeyConstraint(['home_id'], ['Teams_Table.id'], name=op.f('fk_Fixtures_Table_home_id_Teams_Table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Fixtures_Table')
    op.drop_table('Teams_Table')
    # ### end Alembic commands ###
